services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: my-backend:latest
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD
    ports:
      - '5000:5000'

  frontend:
    image: my-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '80:80'

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
    ports:
      - '8080:8080'
    command: ["start-dev"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  postgres_data:
  grafana_data:
